# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb8661abd74670c7b5dd567351eee364e3d3eae778140fa1ffad6e134f1889bd1642a33f35ec63904c71321a39ddf64fcc1c528b29c58864e1d44b41c9c29de3

test:
  secret_key_base: be7e8e5b10bca87f38b9d9d6a83031545f0d3578509e74d88db13fac630538734a8905a767ea3f82dc879ab5d333cd0d16266d4ef4ef88a96d83a742bf75114d

staging:
  secret_key_base: <%= ENV["RAILS_WEBOOK_STAGING_SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
